### ISSUE TITLE
How to use in ReactJS?

### ISSUE THREAD

**Issue by harpreet9629** [elchininet/isometric-css#22]
is there tutorial or steps to use in ReactJs?

**Comment by elchininet** [comment]
Hi @harpreet9629,
You can use it in React in the same way that you use it in regular HTML but just using JSX syntax. [The demo](https://elchininet.github.io/isometric-css/) and the [code example](https://elchininet.github.io/isometric-css/code-example) contained in the documentation are built in React, you can see the source code in the [docs-src folder](https://github.com/elchininet/isometric-css/tree/master/docs-src).
Regards.

**Comment by elchininet** [comment]
Hi @harpreet9629,
Hope you have followed the examples and started to use the library in React. Closing this issue.
Regards.
